package mypkg;
// Generated Jul 2, 2019 4:45:49 PM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int rollno;
     private String sname;
     private Integer marks;

    public Student() {
    }

	
    public Student(int rollno) {
        this.rollno = rollno;
    }
    public Student(int rollno, String sname, Integer marks) {
       this.rollno = rollno;
       this.sname = sname;
       this.marks = marks;
    }
   
    public int getRollno() {
        return this.rollno;
    }
    
    public void setRollno(int rollno) {
        this.rollno = rollno;
    }
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public Integer getMarks() {
        return this.marks;
    }
    
    public void setMarks(Integer marks) {
        this.marks = marks;
    }




}


